### ISSUE TITLE
Display correct user avatar

### ISSUE THREAD

**Issue by matevzmihalic** [wlanslovenija/PiplMesh#113]
Currently we show users avatar from Facebook even if user didn't login with Facebook.

Change user avatar, to use gravatar if user isn't loged in with Facebook.

**Comment by mitar** [comment]
Is not this duplicate of #63?

**Comment by matevzmihalic** [comment]
Yes it is. I didn't find it before.

**Comment by mitar** [comment]
Duplicate. Closing in favor of #63.
