### ISSUE TITLE
Header logo should depend on the language

### ISSUE THREAD

**Issue by mitar** [wlanslovenija/PiplMesh#123]
Header logo should depend on the language. Currently it is only Slovenian version is displayed no matter which language user has selected.

**Comment by aljana** [comment]
What would be better: to make folders for each language or just hardcode language in the image name?

**Comment by mitar** [comment]
Just hardcode in the image name. We will probably support only two languages anyway. :-) And this (I hope) will be only language-dependent image.

**Comment by mitar** [comment]
(You can take another image from wlan slovenija home page, when you switch the language.)

**Comment by mitar** [comment]
Done with #126.
