### ISSUE TITLE
Bug in facebook backend

### ISSUE THREAD

**Issue by domenc** [wlanslovenija/PiplMesh#127]
When I get latest code from GitHub and run it, I get next error:

Error importing authentication backend account.backends.FacebookBackend: "No module named account.backends"

In template d:\IPIRI\PiplMesh\piplmesh\frontend\templates\header.html, error at line 29
Error importing authentication backend account.backends.FacebookBackend: "No module named account.backends"

" {% if user.is_authenticated %}"

**Comment by mitar** [comment]
I doubt you have latest  code. But you are free to fix it. :-)

**Comment by ghost** [comment]
You must delete PiplMesh.0 and PiplMesh.ns from mongo database directory  :)

**Comment by domenc** [comment]
Ty :)

**Comment by mitar** [comment]
Aaa, yes. Django caches information about authentication backend used last time.

You should drop the database, `db.dropDatabase()` in mongo shell (`mongo PiplMesh` in the console).

OK, so this is resolved.

**Comment by mitar** [comment]
That was fast. :-) Under 10 minutes for bugfix. :-)
