### ISSUE TITLE
Design list of online users

### ISSUE THREAD

**Issue by mitar** [wlanslovenija/PiplMesh#141]
Current design list of online users could be improved. For example, small (20x20) user images should be displayed next to the usernames, each entry in the list could be of a fixed width and length, with some scrollbar on the right. Whole list should be sorted, or even sortable. Maybe even searchable/filterable (on top a input box when you enter something that only those entries are displayed). Also some additional information could be displayed bellow the username (second text line, both lines are one user entry), like link to the profile page of this user.

Probably correct way to do this is to keep the list of online uses as a list of user objects in JavaScript, keep it current with updates, and simply just render this list on updates into a placeholder.

Blocked by: #63

**Comment by premik91** [comment]
I know this is to early, but would something like this be okay(this is just design)?
http://shrani.si/f/3x/Gw/3KRkNgmi/userlist.png

**Comment by mitar** [comment]
Why too early?

I would put it in some block somewhere. But yes, something like this.

**Comment by premik91** [comment]
A simple design for list of online users. I also added the toggle animation for hidding it and the title for this 'box' (Active Users or Logged in Users doesn't realy sound good, but that's the least of my worries :)). If you think it's okay, I can make a pull request. A list item should be like:
< img src="#" alt="image" >
user2
< div class="userInfo">information about user< /div >

https://github.com/premik91/PiplMesh/compare/master...Issue-%23141

http://shrani.si/f/11/QQ/1BM3J6M1/loggedinusers.png

**Comment by mitar** [comment]
Where is pull request for this?

**Comment by mitar** [comment]
Please keep objects in JavaScript, as described in ticket description.
