### ISSUE TITLE
Support authentication with and linking to Twitter accounts

### ISSUE THREAD

**Issue by mitar** [wlanslovenija/PiplMesh#151]
Support authentication with and linking to Twitter accounts.

**Comment by lazarm** [comment]
Would be using django social auth good idea (so we could also have support for openID, google etc)? The problem is that social auth doesn't work with mongodb.

**Comment by mitar** [comment]
So obviously the answer is no. :-) Also I think that django social auth does not support linking the same user with multiple authentication options.
