### ISSUE TITLE
Define API for determining user's current location

### ISSUE THREAD

**Issue by mitar** [wlanslovenija/PiplMesh#171]
Define API for determining user's current location based on its IP. For now it can be a mock location, later on we will interface it with real data. Possible locations are among WiFi nodes available in the network.

API should also tell if this is a location based on a WiFi node and which WiFi node this is, with some information about it (name of the node, link to node's webpage, ...). So the idea is that most of the users will be connected over WiFi nodes and will have this information (and based on those they will have also access to information). But some could use mobile or other apps/clients and use HTML5 API (#172) to find location. For those users we will find the closest WiFi node and display information based on that.

**Comment by agiz** [comment]
What should this IP be matched with? We need something like http://www.maxmind.com/app/geolitecity.

Methods 2 (location based on node) and 3 (HTML5) are clear to me.

**Comment by mitar** [comment]
Done.

**Comment by mitar** [comment]
In `request.node` we now have node to which user is connected (`request.node.is_inside_request()` is true) or closest node to user's location (`request.user.is_outside_request()` is true).
