### ISSUE TITLE
Add panel with Google Maps

### ISSUE THREAD

**Issue by mitar** [wlanslovenija/PiplMesh#173]
Add panel with Google Maps, with WiFi node's location on it. Display some additional information about the node in the panel (like name and link to node's webpage).

**Comment by agiz** [comment]
Can you provide a list of current nodes as seen on https://nodes.wlan-si.net/network/map.

**Comment by mitar** [comment]
https://nodes.wlan-si.net/feeds/rss/active/

**Comment by agiz** [comment]
Is this available in JSON format?

**Comment by mitar** [comment]
No? Why? XML is not good enough?

I propose you create a temporary document for nodes, a fixture with hard-coded data which we can inject into the database, and use that. So there is no need to sync from real data for now. Because the interface later on will be different anyway (we will simply read directly from the database).

**Comment by agiz** [comment]
I am not sure if I understand this. You want me to create a new document in models.py with fields reflecting mentioned XML, populate the data from https://nodes.wlan-si.net/feeds/rss/active/ and then in some view, query a database for nodes and render it to end user?

**Comment by mitar** [comment]
For now, I would make it very simple, imply include all nodes in JavaScript object in template. Similar to how we are doing on https://nodes.wlan-si.net/network/map/.

**Comment by agiz** [comment]
Please open and specify an issue for Documents that share common fields regarding geolocation. Maybe that is meant for 
#171 (I do not think so :))? These Document(s) are needed for issues #171, #172, #173, #174 and #175.

**Comment by mitar** [comment]
Yes. It is meant with #171. "For now it can be a mock location, later on we will interface it with real data."

But it could even be hard-coded in Python file. This data. ;-)

I will add to my TODO to prepare interface for this. Maybe it will be eaiser like that.

**Comment by agiz** [comment]
Hm.. Not sure we are talking about the same thing. I was thinking of merely creating Document that has field latitude, longitude, address and some other fields that might be needed and are common in multiple issues. Such Document should then be used by these issues as Embedded Document.

**Comment by mitar** [comment]
Yes. I know. But this could also be simply stored in the file for now. Maybe there is no reason for the database. Will do this.

**Comment by agiz** [comment]
But for now... I will pass all the data there is to end user, pick that user's location at random and display zoomed in map of that location.

**Comment by mitar** [comment]
Good.
