### ISSUE TITLE
Passthrough notification fails

### ISSUE THREAD

**Issue by agiz** [wlanslovenija/PiplMesh#187]
When making request (http://127.0.0.1:8001/updates/home) to pushserver, call fails when notifying main(?) server via passthrough request.
`[24/May/2012 11:07:12] "POST /passthrough HTTP/1.1" 500 63295` in runserver console window. There is no output in runpushserver console window.
### How to recreate an issue:
- Current (latest commit: https://github.com/wlanslovenija/PiplMesh/commit/f61a353d407dc4881cea230e83774532aefbf8c7), clean PiplMesh version
- MongoDB: db version v2.0.4, pdfile version 4.5
- latest requirements.txt
- fresh PiplMesh MongoDB database `PiplMesh`
- newly created users

**Comment by mitar** [comment]
Thanks for reporting.
