### ISSUE TITLE
E-mail address validation

### ISSUE THREAD

**Issue by mitar** [wlanslovenija/PiplMesh#196]
Currently e-mail address is taken for granted when registering or logining through third party authentication mechanisms.

We should add some flag to our user document to mark e-mail address validated or not. After registration or logining through third party we set the flag to false. And on user account change page invite users to validate their e-mail address. Clicking on validation, sends an validation e-mail to that address with users being able to click on the link to validate. If validated, we flip the flag to true.

If user has registered through our system, we can also inform her that this validation is required for password recovery to work.

This is for now. If we will later on require some services using e-mail addresses, we will require a valid e-mail for it and again invite user to validate.

**Comment by premik91** [comment]
You meant something like this(if not tell me, so I won't waste your time)? How should I generate verification link(just some random functions?)?

**Comment by mitar** [comment]
Hm, you code is a bit confusing, so I am not sure if really something like this. ;-) But yes, something along that lines. Maybe check how [django-registration](https://bitbucket.org/ubernostrum/django-registration) does it.

**Comment by mitar** [comment]
So you should read how do to things with class-based views. Then additional confirmation step should be done (never ever do anything in GET, only POST). So make a page where you say that e-mail will be verified (this and this address) by sending a confirmation e-mail there and if they want us to send an e-mail. If yes (POST), send it and then display some result message (you can through messages framework). Then use should get an e-mail with link, open it, this is how e-mail is confirmed (yes, this time we allow GET, but we could still require POST after they open the link, so just a web page with "confirming" button is displayed). And then you flip the flag and display the success message.

Use plain-text e-mail messages.

**Comment by premik91** [comment]
OK :)

**Comment by premik91** [comment]
This is the simplest solution I came up with. 
The user can verify his email when he visits his account page, he clicks the link 'Please verify your email ' and that redirects him to '/account/verification/' (as you wanted). There he can click a link that sends an email(it works, I used python debug tool 'python -m smtpd -n -c DebuggingServer localhost:1025') with generated activation key(length 77). 

There I am not sure how to do it, should I save this activation key to our database(each user has another object, or maybe another model, that contains this activation key as pk and user.username as fk) or I thought we could have a dictionary of these activation keys. It depends, do we want that user must be logged in to verify his email(should we limit the time that activation key works?), or does he just click the link and that's it(email is verified).

**Comment by mitar** [comment]
Just store in the user document. Don't forget to store also creation time of the token. You could define an embedded document and use that.

User should be logged in to verify. We redirect to login if not.
