### ISSUE TITLE
Runpushserver and celeryd not working

### ISSUE THREAD

**Issue by agiz** [wlanslovenija/PiplMesh#200]
When starting mentioned services via manage.py command I get the following output:

```
./manage.py celeryd --loglevel=info --concurrency=1 --maxtasksperchild=10 --beat
Unknown command: 'celeryd'
Type 'manage.py help' for usage.
```

and similar for:

```
/manage.py runpushserver
Unknown command: 'runpushserver'
Type 'manage.py help' for usage.
```
### How to recreate an issue:
- Current (latest commit: https://github.com/wlanslovenija/PiplMesh/commit/8f573f31748d906be45cd480d2d0d9a661b1e415), clean PiplMesh version
- MongoDB: db version v2.0.4, pdfile version 4.5
- latest requirements.txt
- fresh PiplMesh MongoDB database `PiplMesh`

**Comment by mitar** [comment]
Cannot reproduce. Are you sure you used `--no-site-packages` flag when creating virtualenv?
