### ISSUE TITLE
Implement weather panel

### ISSUE THREAD

**Issue by mitar** [wlanslovenija/PiplMesh#210]
Implement weather panel on home page for today and future days. You can also include some nice forecast picture. Find some public domain daily source in English and Slovene, or if not public, Creative Commons, of if not commons, something you use. And at the bottom of the weather panel put attribution link to the source.

**Comment by dcrystalj** [comment]
I found a way to do it, if is ok to you.
Use placefinder api (http://developer.yahoo.com/geo/placefinder/) to convert long. and lat. to yahoo "woeid". Then use this "woeid" to get weather from yahoo weather api  (http://developer.yahoo.com/weather/) ??? 
They allow 50.000 requests per day, and yahoo logo needs to be displayed

**Comment by mitar** [comment]
Mnja mnja. I don't really like it. I don't know. How precise is? Weather APIs are probably a lot around. It would be great to find some precise ones. Especially such which can give you different values for each city in Slovenia. Not just for Ljubljana. We want to be microlocal here! That's the idea of our portal. That you get one information in one part of Ljubljana, and another in another part. Where is this information? Does anybody have it? Can we access it?

**Comment by dcrystalj** [comment]
I couldn't found anything more precise. Even data on Slovenian pages like http://www.vreme-on.net/vremenska-napoved-slika.html or http://www.arso.gov.si/vreme/napovedi%20in%20podatki/vreme_si_w.html is not precise enough to satisfy what you want. I really don't know how you would get forecast on every location if there is no weather station? 
Ivan Pepelnjak said once that all web pages buy same source of weather data to display weather. I think cities in Slovenia are to small to have different forecast on different locations in same city.

**Comment by mitar** [comment]
Then ask him which source we should use. ;-)

There is no raw data from weather stations in Slovenia available online? You could write to arso.gov.si. It is probably public data and should be provided. ;-)

**Comment by dcrystalj** [comment]
I cannot make forecast based on statistic, coz i'm not meteorologist.
If i get current data from weather station i can display only current weather and not for future days ?

**Comment by mitar** [comment]
OK, if it is not clear, we want to give two types of information in this panel: current data and forecast. You can get current data base on microlocation, and general forecast for the area.

**Comment by dcrystalj** [comment]
<b>yr.no:</b> data is free. I tried to use their api ( http://api.met.no/weatherapi/textlocation/1.0/documentation) but it seems that coordinates work only in nederland. Second option here, but I think we should avoid, is parsing webpage http://www.yr.no/place/Slovenia/Other/ajdovscina/long.html. Have forecast.
Terms: display text "Forecast from yr.no"

<b>yahoo</b> -Have forecast.
Terms:  display yahoo logo & PlaceFinder API web service should not exceed 50,000 requests per day. 
<b>vreme.space</b> only few locations & not all places have images/weather only temperature..
<b>meteo</b> only few locations & update interval ==30min && doesn't have image for current weather.

quick data compare for city: Celje
yr.no                         17:00–23:00     22°  //unknown last update time
yahoo                      Last Updated 13:59     22°
vreme.space              15:32:00 UTC+2         23°
meteo.arso.gov.si      15:30 CEST               23° //last update
meteo.arso.gov.si       14:00 CEST          22°

it seems they have same data for current weather. only differenece is how often they refresh it

**Comment by mitar** [comment]
For [yr.no](http://www.yr.no/), it seems they are on the strike: ;-)

> Consequences of the strike: The weather forecasts on yr.no are updated at least four times a day, and will not be affected by the strike. There will be no text forecasts, nor manual corrections of the model forecasts in regions affected by the meteorologist's strike. The strike only affects forecasts in Scandinavia.

In terms there is written that we have to cache data for 10 minutes. So background job is needed anyway for this, as we have discussed that it has to be done for weather anyway as it does not change so much.

But in fact I think we do not really want yr.no, but api.met.no. [See this](http://api.met.no/). And you should not use `textlocation` API (which gives you forecast in text - it is probably normal that there is not much for foreign countries), but `locationforecast` API, [see example](http://api.met.no/weatherapi/locationforecast/1.8/?lat=46.17;lon=14.96).

There is also `weathericon` API and some others (`sunrise` - from that you can get if it is day or night, and get proper weather icon ;-) ).

[vreme.space.si](http://vreme.space.si/) gets data from ARSO and [Weather Underground](http://www.wunderground.com/), where amateur weather reports are being collected.

I would then go and use api.met.no, I think it is the best. Make a background job which fetches current and forecast data and displays it.

**Comment by dcrystalj** [comment]
any tip to get location?

i tried something like this.

from piplmesh import nodes
node = nodes.get_node(request)
node.long
node.lat  

but then i don't have request.. :/ 
please help

**Comment by mitar** [comment]
Location is in `request.node` automatically added by middleware.

Where do you need location? Probably in the view, where `request` is available. So just access `request.node.long` and `request.node.lat` and this will be it.

**Comment by mitar** [comment]
Or you want to get location of all nodes we have? Then you just iterate over all nodes in the background task and check their long and lat.

**Comment by dcrystalj** [comment]
I still don't get it how to access it then from panel.py :-/

**Comment by mitar** [comment]
In `get_context` you can access request with `self.request`. So `nodes.get_node(self.request).lat` would give you latitude.

**Comment by dcrystalj** [comment]
it works, thanks

**Comment by dcrystalj** [comment]
Can you please tell me how you want the data to be displayed like? link to any simmilar solutions?

**Comment by mitar** [comment]
Hm, no idea. So for now just display things in the panel. So find closest location with weather data to user's node location. And display then current information (temperature and cloud/sunny sign). And then also for tomorrow and day after tomorrow.
