### ISSUE TITLE
Implement OpenStreetMap layer in our map panel

### ISSUE THREAD

**Issue by mitar** [wlanslovenija/PiplMesh#215]
[OpenStreetMap](http://www.openstreetmap.org/) is an open alternative to Google Maps and proprietary maps. It can be integrated with Google Maps API and it would be good to do that. An example [can be found here](http://dev.wlan-si.net/ticket/367).

**Comment by mitar** [comment]
Done. #307 still has to be done.

**Comment by stefanb** [comment]
Hmmm...
![Screenshot](http://dev.wlan-si.net/raw-attachment/wiki/PiplMesh/screenshot.png)
"October 7 2012 version" na strani http://dev.wlan-si.net/wiki/PiplMesh ima še vedno google maps (oz vsaj njihov logotip).

**Comment by mitar** [comment]
OpenStreetMap is currently added just as a layer, and a non-default one, too.

See #307, too.
