### ISSUE TITLE
Add about page for the portal

### ISSUE THREAD

**Issue by mitar** [wlanslovenija/PiplMesh#243]
Add about page for the portal, probably somewhere in the footer, with short description what the portal is, that it is a part of wlan slovenija initiative, who made it (a list of contributors, usernames probably, you can link to their GitHub profiles, you could fetch this dynamically in the background job regularly). That it is open source, that code can be available here, that any issues can be reported here, that people are invited to contribute to the portal.

Some help can be found here:

http://dev.wlan-si.net/wiki/PiplMesh

**Comment by mitar** [comment]
A list of contributors is not yet done.

**Comment by dcrystalj** [comment]
these data should be saved periodically an then displayed or just rendered and displayed "on fly"?

**Comment by mitar** [comment]
Depends how you want to render it on the fly. If you want that server fetches them in the request-response cycle, then this is no go. But if client can fetch this from somewhere with JavaScript and display it, then this could be a nice way.

So if this later is possible, we could do it. If not, we need to fetch it in the background.
