### ISSUE TITLE
Improve User account/profile design

### ISSUE THREAD

**Issue by borismarn** [wlanslovenija/PiplMesh#273]
I hope I haven't overlook but I haven't seen any issues/pull requests regarding user account/profile page design. I think there is some room for css/html improvements in account.html, user.html... Like replacing class="registration" on divs that are not about registration, changing menu div to menu ul, changing the style of #menu_list (so that it wouldn't need position:absolute), titles (h1) and few other things.

I've made a branch with few changes in this direction, still not finished though.
https://github.com/BorisMarn/PiplMesh/commit/30387c9d5acb8be24a7c4d0d3d08b1ff4a4d052e

Would this be something worth doing?

**Comment by mitar** [comment]
Yes. That could be improved. Especially that menu could be moved out of the template to a separate file. Or maybe even a new base template file could be made which would have account menu at the side, and then all account-related pages could extend that one.
