### ISSUE TITLE
Remove disconnected users

### ISSUE THREAD

**Issue by zupan** [wlanslovenija/PiplMesh#289]
Users that are disconnected are not removed from online user list.

**Comment by mitar** [comment]
Oh, I thought you did a pull request. ;-)

**Comment by mitar** [comment]
It works for me quite nicely?

Maybe you have some stale data in the database. If you shutdown push and http server before closing all tabs with PiplMesh, this could happen.

**Comment by zupan** [comment]
I dropped my database and still have this problem. When i was writing new code i found out that "connections__in=([], None)," in frontend/tasks.py was causing problems.  Also i think there is a problem with javascript for deleting disconnected users from user list.

Are disconnected users working fine in your environment?

**Comment by mitar** [comment]
How exactly are you testing this? So I delete database, I run all three daemons, I open PiplMesh in two different browsers. I see both users appear. I close one browser, that user disappears in the other browser.

**Comment by zupan** [comment]
I am doing exactly the same thing. I even created new virtualenv. I guess there is no reason for this issue if everything is fine on your end. But i think i wasn't the only one that had this problem.

**Comment by mitar** [comment]
OK. We can leave it open, maybe somebody else will be able to shed some light on it.

Sorry, but if I cannot reproduce it, I cannot help. So yes, I know that there are some issues if daemons go down, but if they run normally, connecting and disconnecting should work.

Which version of MongoDB you have?

**Comment by zupan** [comment]
I am using MongoDB version 1.8.2 on ubuntu. Maybe this is the reason.

**Comment by mitar** [comment]
I am using v2.0.6. I think we have in prerequisites written, that we need 2.0+ MongoDB:

https://github.com/wlanslovenija/PiplMesh/blob/master/docs/installation.rst#prerequisites

**Comment by zupan** [comment]
Sorry my mistake. I was also using v2.0.6, when i was on windows, but i wasn't careful when i switch to ubuntu.

**Comment by mitar** [comment]
So it works now for you on Ubuntu, too, when you switched to 2.0.6 there?

**Comment by zupan** [comment]
After upgrading to 2.0.4 online user list is working perfectly fine. Sorry for all the inconvenience.

**Comment by mitar** [comment]
Great! And no problem. Just that it works.
