### ISSUE TITLE
Allow staff users to switch/mock location

### ISSUE THREAD

**Issue by mitar** [wlanslovenija/PiplMesh#293]
Allow staff users to switch/mock location easily. Maybe there could be additional all present menu entry in the top right menu (next to logout) with drop-down options for staff users. This should be displayed and should work only for staff users.

This could be done with storing special entry into user's session which would override value returned by our nodes API.

If you have other ideas for what this drop-down menu could provide, suggest, implement, or open a ticket.

**Comment by mitjap** [comment]
I will put drop-down menu in header.html and make all views (that include header.html) inherit new class that can provide all nodes from piplmesh.nodes.get_all_nodes(). Changing this drop-down would switch/mock location the way it is described above.

Is this solution ok?

**Comment by mitar** [comment]
> I will put drop-down menu in header.html

Good.

> make all views (that include header.html) inherit new class that can provide all nodes from piplmesh.nodes.get_all_nodes()

Ehm, what? You probably have to learn about context processors.

**Comment by mitar** [comment]
There is still user feedback missing that mocking is in progress and to which node it is locked. Probably just have to provide initial data to the form.

**Comment by mitar** [comment]
Check what the view does if form validation fails.
