### ISSUE TITLE
Add bitcoin wallet field for maintainer 

### ISSUE THREAD

**Issue by wrought** [wlanslovenija/PiplMesh#331]
Generally may be valuable to extend the number of fields available for information about maintainers.

Suggestion came from a sudo mesh meetup attendee who thought it would be a great incentive to allow maintainers to host bitcoin wallets to encourage donations for their efforts.

**Comment by mitar** [comment]
Are you sure this is the right place for this ticket? You probably mean this for nodewatcher? Please open a ticket at [wlan slovenija development Trac](http://dev.wlan-si.net/).

BTW, user model and registration form is what each instance of nodewatcher configures by itself. It is simply using Django user model. So yes, you can add any field you want, and expose that then publicly.

Example of this is the field for attribution. We are using custom field for wlan slovenija to ask users how they want to be attributed, with username, full name, or hidden. Then we display this [here](https://wlan-si.net/en/by-people-for-people/).

**Comment by mitar** [comment]
On the other hand, you might like [this idea](http://dev.wlan-si.net/ticket/833).

**Comment by wrought** [comment]
Ah woops, you're right, sorry about that. Will post in trac.
