### ISSUE TITLE
Display Google search results inside the portal

### ISSUE THREAD

**Issue by mitar** [wlanslovenija/PiplMesh#4]
Display Google search results inside the portal and not redirect to the Google itself. In this way we can retain users on our portal and later on also integrate our own results from the portal.

Ads provided by Google for user searches should be displayed so that we can [monetize](https://www.google.com/adsense/static/en_US/WsOverview.html) that we have a Google search form integrated.

**Comment by mitjap** [comment]
If we are to implement this progamatically (and not just including google's page with iframe or someting similar) this API is the best way to do it (http://code.google.com/apis/customsearch/v1/overview.html). Unfortunately free plan is limited by 100 queries per day. Do we proceed with this issue?

**Comment by mitar** [comment]
No, there is also Google Custom Search approach. That API is if you want directly the results and use them for yourself. We do not mind that results are displayed by Google and that Google add its ads.

**Comment by mitjap** [comment]
There are two ways to do this. One way is to do this programmatically as described above, and the second way is by using javascript that handels the search. 

Here are links to both solutions.
http://www.google.com/cse/
http://code.google.com/apis/customsearch/

I gues  javascript solution that emphasizes results on wlan-si.net and PiplMesh and also searches the web would suit as well.

**Comment by mitar** [comment]
CSE also search the web and is not limited to number of queries as I understand:

https://code.google.com/apis/customsearch/docs/js/cselement-devguide.html
https://code.google.com/apis/customsearch/docs/js/rendering.html

I think we would just have two sections in the results. Our own results + Google results.

**Comment by mitar** [comment]
Done with #47.
