### ISSUE TITLE
Usernames should be case-insensitive

### ISSUE THREAD

**Issue by mitar** [wlanslovenija/PiplMesh#41]
In Django, usernames (for model-based authentication) are by default case-sensitive. This is really crazy and it would be great to make them insensitive, but case-preserving. (Passwords should still be sensitive, of course.)

**Comment by aljana** [comment]
Do we have to allow miXeD-case letters for username or can we simply convert letters to lowercase?

**Comment by mitar** [comment]
Updated issue description.

Usernames should be case-preserving. ;-)

Hint: Check our regular existing project we are stealing from. ;-)

**Comment by aljana** [comment]
Ok I see, but this requires changes in account/forms.py, which is also used by issue #9. So when I make pull request, should the file only contain function that is necessary for this issue? But then it won't work until it's merged?

**Comment by mitar** [comment]
Yes, you have coordinate this with your team. You can make a pull request together for both tickets if there is really no way to split it. Or you could wait (this is why it is in "bonus" milestone) and do it some other time.

**Comment by mitar** [comment]
Or, you could even make two pull requests for this issue, one which is independent of the #9 and one which depends on the pull request of your team. In this way we could pull at least a part of your changes even if some other team's #9 pull request is pulled in at the end.

**Comment by mitar** [comment]
Done with #102.
