### ISSUE TITLE
Design - frontend like wlan slovenia

### ISSUE THREAD

**Issue by NejcZupec** [wlanslovenija/PiplMesh#51]
Basic frontend layout from wlan slovenia site.

**Comment by mitar** [comment]
I agree. Where is code? ;-)

**Comment by mitar** [comment]
I found it. ;-)

**Comment by mitar** [comment]
I [made public](http://dev.wlan-si.net/browser/homepage) current code for wlan slovenija homepage. It could be easier to work on this now.

**Comment by mitar** [comment]
Done with #52.

**Comment by mitar** [comment]
For design ideas I recommend you also check [nodewatcher](https://nodes.wlan-si.net/) web page (for example how to design login).
