### ISSUE TITLE
List of currently logged in users

### ISSUE THREAD

**Issue by mitar** [wlanslovenija/PiplMesh#65]
On home page provide a list of currently logged in users. Maintain the list up-to-date also after the page has been opened. Do this using HTTP push for real-time updates.

For now use `onbeforeunload` JavaScript event handler to signal the server that user is closing the page (but be careful if the page is opened multiple times).

Use [django-pushserver](https://github.com/mitar/django-pushserver) app for HTTP push support.

**Comment by agiz** [comment]
To start this topic... If one should use `onbeforeunload` as a signal for user parting, what shall be used for user joining? We could just assume users join whenever they connect to the site but there is an issue of having ghost users, that is, the users without javascript. So is it ok to send asynchronous request when user connects as a signal that she joined and has a browser with javascript support?

**Comment by mitar** [comment]
Hmm. A very good point. I have not thought about that.

So we would really need to get information from nginx when user connects and when user disconnects. I will extend django-pushserver with this.

**Comment by agiz** [comment]
Well, you can extend django-pushserver but this will make it less similar to nginx environment. As I mentioned in email correspondence I think there is no signal currently in nginx that detects connections terminated by client. 

For starters try connecting to nginx push server with Chrome (I am using Chromium) and abort the connections and you will see that nothing happens because it terminates silently. There is more :). You can still have an open socket and not even be on the website (ie if you close the site but have an image open from this site in another window).

I suggest we go back to pinging and timeout.

**Comment by mitar** [comment]
In the worst case we will run django-pushserver in the production. :-)

**Comment by mitar** [comment]
Test it out and give feedback. :-)

**Comment by mitar** [comment]
I would recommend that you extend User document with two fields:
- list of open channels with subscription time
- time of last unsubscription

So if the first has any elements, then user is logged in. If it is empty and the second field is more then X seconds in the past, the user is logged out.

**Comment by agiz** [comment]
What can be used to fire delayed events? I want to use something already implemented in django and not some external package. Also this delayed event must have an option to be canceled. Something similar to javascript's `setTimeout`.

**Comment by mitar** [comment]
You cannot. Things are processed always inside of the request handler. This is synchronous operation. And you want that it is very quick (user waits longer for delay). Django signals are also synchronous signals. All this is by design. So the idea is that you just very quickly store stuff and then process things in the background. This is what we will be doing in the future with Celery. So probably then we will have some regular task which will check every 30 seconds for example status of users and send updates if things change.

**Comment by mitar** [comment]
BTW, there is completely nothing wrong with using existing other libraries. Django is quite conservative with features.

**Comment by mitar** [comment]
So for now you can improvise. For example, use pushserver passthrough only for adding the user to the list, and onbeforeunload for removing the user from the list.

**Comment by mfrlin** [comment]
How do we install your version of pushserver? What version do we get from pip install django-pushserver ?

**Comment by mitar** [comment]
Should be latest version. Check on [PyPI](http://pypi.python.org/pypi/django-pushserver).

**Comment by mitar** [comment]
My version of pushserver is the official one, if this is maybe not clear. :-)

**Comment by agiz** [comment]
I am still have seconds thought about this before I pull... I want to discard/ignore this instant subscribe and unsubscribe actions. I tried couple ways but still not satisfied with results.
1. With celery: I trigger countdown on unsubscribe action that can be (is) canceled wherever subscribe action is triggered. I am assigning celery's task id as session id. If I cancel (and mind you, this is happening sequentially) this task and then later start this task again as before in unsubscribe (same countdown, same task_id), it will get canceled too.
   Like this:

reload

```
unscb : ->  start 10s counter that logs user out
 subs  : ->  if this is within 10 seconds, cancel this task
+-+-+-+-+-+
leave website: ->start 10s counter that logs user out
subs: -> timeouts (not even triggered) so task should get executed.
```

Task is still revoked.
1. MongoDB: count subscriptions in one field and unsubscriptions in the other then do something in the background with some interval task. My question here is, how thread(?) safe is mongo? I read that I should treat mongo data as a snapshot in the past so this my not be good approach either. 

I want to solve this without `onbeforeunload` hack.

Is it possible to modify django-pushserver to group passthrough subscriptions/unsubscriptions. For example append some ID that is immediately discarded if match is made?

**Comment by mitar** [comment]
Aaah. Not do it like this. First, never assign celery task ids manually. They should be unique.  Just leave them as they are (you can create your own mapping if needed in the database).

You do not want to use thread in Django. Do not do background processing in Django. This is not what it is meant to do. Yes, Django is thread safe, but so that it can process multiple requests in threads, not for background tasks. Use celery for background task.

Then, changing the pushserver is also not a good idea. You want to keep things modular. Every module should do exactly the thing it is meant to do. Not mix things. For example, Django knows how to map requests to users. pushserver has no idea about this. Complicating things with some id means you have to keep track of that, for how long, where (in memory?), what if we will have multiple push servers because we will have so many users? How will they be kept in sync?

No, push server does only one thing, keeps long polling connections open. Django generates content. Nginx deals with clients. Celery runs things asynchronously.

OK, and back to your idea. It is not good. It is not good because it does not solve the main issue: that you do not want to process anything for each individual subscribe/unsubscribe notification. We do not need so responsive system. Nobody expects it. And moreover, it means that processing load increased with number of clients. You want to always go around that if it is possible.

So idea is not to "fork" a processing into the background in the way you are doing now. Sending a task and then killing.

The idea is that you just store data in the database. And that then you have an independent, asynchronous, in no manner connected to how user subscribe or unsubscribe, background process doing its stuff at its own pace.

So what you should do is: just store data in the database, do not create tasks in Celery. This is also expensive. And then define a periodic independent task which runs for example every 30 seconds and processes this data. Sees what is new state, who has been added, who removed, sends to the user current list (or deltas), whatever is needed.

**Comment by agiz** [comment]
So `{ $inc : { field : value } }` is safe and I will get the correct number of open tabs/connections from a user no matter what.

**Comment by mitar** [comment]
I don't understand what are you saying or where you need this, but yes, this is atomic.

**Comment by agiz** [comment]
Need this for counting open connections for user. And on the other part to decreasing this count. 
However there are some bugs but too tired now to figure it out. It works well when there are no ajax calls to the site. As soon as I use `updates.send_update(channel_id, data)` with refresh there are way more un-subscriptions than subscriptions so the value goes below zero.

**Comment by mitar** [comment]
I think you should not just count them, but for each user have a list of subscribed channels. No?

**Comment by agiz** [comment]
I am counting how many times has one particular user connected to the site. If she closes one connection she still has \x -1 opened connectons therefore we cannot disconnect her. I don't have perfect setup and I think something goes wrong when I call updates.send_update.

**Comment by mitar** [comment]
This count is then the length of the list. I am saying that maybe you will need to store additional data then just the count. Data which will help you mach subscribe signals with unsubscribe signals. Maybe you do not need this and counter is good enough. But maybe you do.

I think it is better to keep this information, to not just count, but to exactly know what is user being subscribed to. Especially if we will later on use subscription for each wall. Then this list will be a list of things the user is really subscribed to. This could be an interesting information to have.

**Comment by mitar** [comment]
I updated push server, now it provides two types of signals.

**Comment by mitar** [comment]
Done with #122. We didn't use `onbeforeunload` JavaScript event handler, but are using background Celery task to regularly check online status of users.
