### ISSUE TITLE
Define Tastypie document type for MongoEngine

### ISSUE THREAD

**Issue by mitar** [wlanslovenija/PiplMesh#67]
Define [Tastypie](http://tastypieapi.org/) document type for [MongoEngine](http://mongoengine.org/).

We will be using [Tastypie](http://tastypieapi.org/) for REST interface (but if you find some better library, tell). It does not yet have support for [MongoEngine](http://mongoengine.org/) but it is possible to define [your own data sources](http://django-tastypie.readthedocs.org/en/latest/non_orm_data_sources.html). It should be defined similar to official `ModelResource` for Django ORM (Django models). For example, it should automatically be able to [view schema](http://django-tastypie.readthedocs.org/en/latest/interacting.html#inspecting-the-resource-s-schema) of the MongoEngine document. Probably you will have to define also new/custom data fields.

Maybe there exist something already on the web. Search. ;-) If not, develop this as an independent project, creating pull request against [this repository](https://github.com/mitar/django-tastypie-mongoengine).

**Comment by matevzmihalic** [comment]
Can you create initial commit to django-tastypie-mongoengine, so I can fork it?

**Comment by mitar** [comment]
Done.

Check also one other [implementation](https://github.com/andresdouglas/django-tastypie-nonrel) of Tastypie interface for MongoDB.

**Comment by mitar** [comment]
And it would be great if something like ModelForm would also exist for MongoEngine. But this is probably some other ticket/project, no?

**Comment by mitar** [comment]
Done with https://github.com/mitar/django-tastypie-mongoengine/pull/1.
