### ISSUE TITLE
REST interface for posts and comments

### ISSUE THREAD

**Issue by mitar** [wlanslovenija/PiplMesh#68]
Define [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) interface for posts, comments, and attachments. We will probably use [Tastypie](http://tastypieapi.org/) and its MongoEngine extension [django-tastypie-mongoengine](https://github.com/mitar/django-tastypie-mongoengine), but you can also research other libraries. Tastypie takes care of defining the API, like query and format interface, but we still have to define URL structure. Let it be like:

```
/api/post/
/api/post/id/
/api/post/id/comment/
/api/post/id/comment/id/
/api/post/id/attachment/
/api/post/id/attachment/id/
```

IDs in MongoDB are not numerical/sequential values. You will have to play a bit with [nested resources](http://django-tastypie.readthedocs.org/en/latest/cookbook.html#nested-resources).

For now, for API authentication, use Django authentication (so authentication of the Django request). Or even more: simply allow everything.

**Comment by matevzmihalic** [comment]
If we have different documents for `Post` we can't have a structure you described above.
We would have to have `/api/textpost`, `/api/imagepost`,...
If we want to have only `/api/post`, we must change our document for Post.

**Comment by mitar** [comment]
Can we override saving method so that we have some "type" field value which specifies "text", "image" or something and according to that correct Post child class is used when saving?

**Comment by maticko** [comment]
This pull is not fully working yet, but some comments would be great, to see if we are on right way to solve this problem.

**Comment by mitar** [comment]
Done with 4b8639ac766c1652698e78e5f3bb5a5f47f5b725.
