### ISSUE TITLE
Implement django-lazyuser for MongoDB

### ISSUE THREAD

**Issue by mitar** [wlanslovenija/PiplMesh#69]
Implement something like django-lazyuser for MongoDB. So that also temporary users would be in MongoDB. Because we are implementing now everything ourselves, we can use only one user model/object with all needed fields.

I would just change decorator django-lazyuser users into additional middleware which would in practice be very similar, but would automatically be applied to all requests (which is I believe what we want).

**Comment by aljana** [comment]
Is it allowed to use some code from django-lazysignup or it must be written from start? I'm not planning to do this (most probably), just curious. :)

**Comment by mitar** [comment]
Oh, good to mention. I have to fix this ticket's description first. I don't believe that the way proposed above is the best anymore. :-)

**Comment by mitar** [comment]
OK, changed description. Now to the answer: you will have to write your own because to many things are different. For example, we can use the same user object, just add a flag (in any case it would be good to add two flags: `is_registered` and `is_email_verified`, currently we do not have any e-mail address verification).

**Comment by mitar** [comment]
You can look at django-lazysignup, but please write your own, because of the licenses issues. We could use their code because it is BSD licensed, but then we will have to add some text to our license that our code incorporates code from them under such and such conditions. We can do that, if really necessary, but try without. :-) If you do, then please [read this](https://www.softwarefreedom.org/resources/2007/gpl-non-gpl-collaboration.html) and accordingly update our `LICENSE` file in a pull request. (We do not use license headers in the code.)

**Comment by domenkozar** [comment]
Why do you use mongodb for everything? Django - batteries included. Except that you are ditching all the batteries you get. It's like getting Pamela Anderson for a girlfriend but then operating her tits to size A.

**Comment by mitar** [comment]
We want to feel pure and close to batteries. :-) Not artificial. :-)

But it is not true. The fundamental goal of Django is [loose coupling](https://docs.djangoproject.com/en/1.4/misc/design-philosophies/#loose-coupling):

> A fundamental goal of Django’s stack is loose coupling and tight cohesion. The various layers of the framework shouldn’t “know” about each other unless absolutely necessary.
> 
> For example, the template system knows nothing about Web requests, the database layer knows nothing about data display and the view system doesn’t care which template system a programmer uses.
> 
> Although Django comes with a full stack for convenience, the pieces of the stack are independent of another wherever possible.

So, Django is great as a pedagogical tool: it has great documentation, very well written code and it is full of best-practice approaches you can just learn from. On the other hand, we want to showcase modern technologies, especially technologies "big" are using (like non-relational databases), so yes, we are a bit forcing them sometimes. But the idea is to get to know them and learn about them.

So this project is in the first line a project for students to learn (based on goals of the course, which is [here](http://ucilnica.fri.uni-lj.si/course/view.php?id=226)). In the second also that something useful comes out, something which will really be deployed.

**Comment by mitar** [comment]
And you are welcome to join the development, if you want. Or that of [nodewatcher](https://github.com/wlanslovenija/nodewatcher).

**Comment by domenkozar** [comment]
If you ditch django orm, basically 90% of contrib modules are useless regardless of loose coupling it is trying to achieve. I crawled through issues and there is a lot of reimplementation of what django provides because you are ditching it's orm.

Django has also some really bad practices, like User model (which is completely not extendable). If you want to show modern technologies I would recommend pyramid:

http://pyramid.readthedocs.org/en/1.3-branch/index.html

**Comment by domenkozar** [comment]
Otherwise I think it's a great idea for students, they might learn something from real world web development for a change ;) Congratz!

**Comment by domenkozar** [comment]
One important lesson when using frameworks to learn is to NEVER go against them. It will cost you too much time, money and tears.

**Comment by mitar** [comment]
Yes, I know it, but still opted for Django because it has bigger and better community so it is easier to Google for various issues you can have.

Again, it is good that they can reimplement things - this is the way to learn. Reading the code, changing it a bit. They will also maybe learn that sometimes it is not the best to take the newest tool and try use it. :-)

**Comment by mitar** [comment]
I completely agree with your last statement. :-)

And for students, I also think that it is good for them that somebody is commenting on their code. That it is not just the question to do it, but also how. This I really missed when I was studying. Nobody saying for the code what is good and what is bad. (Of course nothing is absolute, but at least some guidance.)

**Comment by domenkozar** [comment]
I would disagree with reimplementing things to learn something new. Being engineer brings many benefits, and one of many major is to be paid to research. There are too many problems our there to solve to lose time on re implementing what works.

I agree - using github is a HUGE step forward. I hope it becomes a practice! When students are finished, you can poke me and I will help with reviews!

**Comment by mitar** [comment]
I agree, and I hope students will fast get past those initial phases so that we will be able to start developing new stuff. But they have problems even when they have already a similar implementation at hand, so ...

I am reviewing code as they work, on pull requests.

But I have an idea. We could "invite" you as an external evaluator of the whole project at the end to one class. And you could say your opinion. What you think is good, what is bad. What we did well, what could be done differently. So that they hear also some other opinion and not just mine? (And learn that there are multiple truths and multiple ways.)

**Comment by domenkozar** [comment]
I would love to do that, but I'm back to slovenia in end of June. Is that too late?

**Comment by mitar** [comment]
Hm. You do have Skype there where you are? :-) (Where you are?)

BTW, thanks for hijacking the issue. :-)

**Comment by domenkozar** [comment]
skype: domenkozar

Currently located in Barcelona :) Sorry for spamming non-relevant issue!

**Comment by mitar** [comment]
The idea was that you could call in over Skype and present your evaluation. :-)

**Comment by mitar** [comment]
Done some time ago.
