### ISSUE TITLE
Support Facebook Connect for registering our users

### ISSUE THREAD

**Issue by mitar** [wlanslovenija/PiplMesh#7]
Support [Facebook Connect](https://www.facebook.com/help/?page=229348490415842) for registering/login of our users. We could retrieve some additional information about our users. We could also be a bit viral and try to get information about all user's friends so that we can automatically match our users together and connect them also on our portal so that they do not need to find their friends manually again.

**Comment by dcrystalj** [comment]
It's necessary to have APP_ID from facebook which is given when you register your website as developer on facebook.
Should I pullrequset the code without ID?

**Comment by mitar** [comment]
Register app id for 127.0.0.1:8000 IP and port (if possible, otherwise for localhost:8000) and commit that. For production we will use other app id.

**Comment by mitar** [comment]
Done with #48.
