### ISSUE TITLE
Change facebook avatar to gravatar

### ISSUE THREAD

**Issue by domenc** [wlanslovenija/PiplMesh#72]
Current situation: 
When you register (normal, not Facebook) in PiplMesh and then login in -> get picture from Facebook based on username not an e-mail. So when I register it with username "mitar" then I get a picture user "mitar" and don't get picture based on my email.

Fix it that based on user email with use a gravatar services

**Comment by mitar** [comment]
Not good. As we said we have to abstract avatars in the way that if the user is logged in through Facebook, Facebook profile image is displayed, if she is logged in directly, gravatar is displayed. See #63. We also said that we will probably simply define a method on our MongeEngine user document/class, which will return the avatar for the given user and will depend on the type of the user.
