### ISSUE TITLE
Search query string should be simplified

### ISSUE THREAD

**Issue by mitar** [wlanslovenija/PiplMesh#74]
Search query string should be simplified, currently some parameters are passed around which are not necessary as they are constant. Only user parameters should be in query (like search keywords).

**Comment by ghost** [comment]
This must be some kind of bug. when I was implementing this feature in url only query was passed. For example if your search word was "test" url looked like http://localhost:8000/search?q=test and also queries on google looked like http://www.google.com/search?q=test. So probably this is something google changed.

**Comment by mitar** [comment]
In any case: it should be fixed. ;-)

**Comment by ghost** [comment]
I think this is fixed now. Now url looks like http://localhost:8000/search?q=asdadsd
Please check if your url also looks like that and you can close the Issue. :)

**Comment by mitar** [comment]
Where is pull request?

**Comment by ghost** [comment]
Ididnt do anything, its just fixed... ;)

**Comment by mitar** [comment]
Hm, it also works for me. Interesting. ;-)

**Comment by ghost** [comment]
Yeah, probably this was some google issue. :)
