### ISSUE TITLE
Structure CSS file

### ISSUE THREAD

**Issue by mitar** [wlanslovenija/PiplMesh#81]
We had a very nice CSS file structure, indented in accordance with DOM structure. Currently CSS file is not anymore likes this. It should be made again.

**Comment by premik91** [comment]
Is this what you meant?

**Comment by mitar** [comment]
I am not sure. ;-) But I think it has to follow also DOM structure, (`li` is inside the `ul`) not selector specificity. (The later is sometimes, but not always, related.)

**Comment by premik91** [comment]
This is now done as in the first request.

**Comment by mitar** [comment]
Pull request please.

**Comment by mitar** [comment]
I give up on this ticket. Just everybody try to make a readable CSS while you change it.
